openapi: 3.0.0

info:
 title: HTree API
 version: 1.0.0
 description: CRUD operations via tree-based structures

servers:
 - url: /pg

tags:
 - name: Structure 
   description: working with structures itself
 - name: Tree
   description: operations with tree data 
 - name: Properties
   description: work with node's properties

paths:
 /structure:
  post:
   summary: Create structure
   tags:
    - Structure
   requestBody:
    required: true
    content:
     application/json:
      schema:
       $ref: '#/components/schemas/setStructureRequest'
   responses:
    200:
     description: success
  get:
   summary: get structure list
   tags:
    - Structure
   responses:
    200:
     description: success     
 /tree/node:
  post:
   summary: Create tree node for existing structure
   tags:
    - Tree   
   requestBody:
    required: true
    content:
     application/json:
      schema:
       $ref: '#/components/schemas/setTreeNode'
   responses:
    200:
     description: success     
  put:
   summary: change tree node position and name
   tags:
    - Tree   
   requestBody:
    required: true
    content:
     application/json:
      schema:
       $ref: '#/components/schemas/updateTreeNode'
   responses:
    200:
     description: success         
 /tree/node/{id}:
  get:
   summary: get node by id
   tags:
    - Tree   
   parameters:
    - name: id
      in: path
      schema:
       type: string
      required: true
   responses:
    200:
     description: success     
  delete:
   summary: delete node by id
   tags:
    - Tree   
   parameters:
    - name: id
      in: path
      schema:
       type: string
      required: true
   responses:
    200:
     description: success         
 /tree/{structureid}:
  get:
   summary: get whole tree for structure
   tags:
    - Tree   
   parameters:
    - name: structureid
      in: path
      schema:
       type: string
      required: true
   responses:
    200:
     description: success 
 /property:
  post:
   summary: create property for node
   tags:
    - Properties   
   requestBody:
    required: true
    content:
     application/json:
      schema:
       $ref: '#/components/schemas/setProperty'
   responses:
    200:
     description: success 
  put:
   summary: update property
   tags:
    - Properties
   requestBody: 
    required: true
    content:
     application/json:
      schema:
       $ref: '#/components/schemas/updateProperty'
   responses:
    200:
     description: success 
 /property/{treeid}:
  get:
   summary: get properties for node by node id
   tags:
    - Properties   
   parameters:
    - name: treeid
      in: path
      schema:
       type: string
      required: true
   responses:
    200:
     description: success     
 /property/{id}:
  delete:
   summary: delete property
   tags:
    - Properties   
   parameters:
    - name: id
      in: path
      schema:
       type: string
      required: true
   responses:
    200:
     description: success       
 /property/types/{structureid}:
  get:
   summary: get all types for structure
   tags:
    - Properties   
   parameters:
    - name: structureid
      in: path
      schema:
       type: string
      required: true
   responses:
    200:
     description: success         
              
     

components:
 schemas:
  setStructureRequest:
   type: object
   properties:
    name:
     type: string
     example: Tree
  setTreeNode:
   type: object
   properties:
    structureid:
     type: string
    parentid:
     type: string   
    name:
     type: string      
  updateTreeNode:
   type: object
   properties:
    id:
     type: string
    name:
     type: string
    parentid:
     type: string      
  setProperty:
   type: object
   properties:
    type:
     type: string
    treeid:
     type: string   
    value:
     type: string          
  updateProperty:
   type: object
   properties:
    id:
     type: string   
    type:
     type: string
    treeid:
     type: string   
    value:
     type: string        
   